# get all users
GET http://localhost:8080/api/users/

###
# delete all users (and also all workouts)
# DELETE http://localhost:8080/api/users/

###
# get user
GET http://localhost:8080/api/users/6836dad19ee670eebe7ab9b0

###
# create a user
POST http://localhost:8080/api/users
content-type: application/json

{
  "email": "wzielinski@bulkybull.com",
  "firstName": "Wojciech",
  "lastName": "Zieliński",
  "weight": 82,
  "height": 183,
  "age": 29
}

###

# get all workouts for user
GET http://localhost:8080/api/users/6836dad19ee670eebe7ab9b0/workouts

###
# get single workout for user
GET http://localhost:8080/api/users/68338d2bb07d6603835081f8/workouts/6834f943230b1ea85ee43492

###
# create workout for user
POST http://localhost:8080/api/users/6836dad19ee670eebe7ab9b0/workouts
content-type: application/json

{
  "date": "27/05/2025",
  "exercises": [{
    "exercise": "68362f7a67b59b7bf1e622d7",
    "comment": "as a warm up",
    "sets": [{
      "reps": 6,
      "weightKg": 0
    }, {
      "reps": 8,
      "weightKg": 0,
      "thoughts": "those 8 reps were easier than 6 reps in the first set"
    }, {
      "reps": 10,
      "weightKg": 0,
      "thoughts": "last rep was not easy"
    }]
  }, {
    "exercise": "68362f7a67b59b7bf1e622dc",
    "comment": "quite nice handstand",
    "sets": [{
      "timeSec": 3,
      "thoughts": "First I touched the wall and then hold it"
    }, {
      "timeSec": 5,
      "thoughts": "First I touched the wall and then hold it"
    }, {
      "timeSec": 7,
      "thoughts": "First I hold it and then slightly touched the wall"
    }]
  }]
}

###
# delete a single workout from user
DELETE http://localhost:8080/api/users/68338d2bb07d6603835081f8/workouts/6834fa235ea4807be6e31b2b

###
# delete all workouts from user
DELETE http://localhost:8080/api/users/68338d2bb07d6603835081f8/workouts

###
# delete a single user
DELETE http://localhost:8080/api/users/683763cf6e426623b62b3faa